-- schema.sql
--
-- SUPERSEDED. The canonical database definition now lives in
-- database/migrations/ as an ordered, idempotent set:
--
--   000_extensions.sql        extensions (pgcrypto, pg_trgm)
--   001_content.sql           question-bank tables + updated_at triggers
--   002_profiles.sql          profiles + auto-create trigger (003 fix folded in)
--   003_user_ecosystem.sql    plans, subscriptions, payments, attempts
--   004_rls.sql               Row Level Security + policies
--   005_seed.sql              default subscription plans
--
-- Run them IN FILENAME ORDER on a fresh Supabase project (SQL Editor,
-- or `supabase db push`). Do NOT run this file — it is a pointer only.
